# @author : Julien Pechberty
#
# https://help.github.com/en/actions
name: setup symfony prohect TaskFile Testing
on:
  push:
    branches:
      - testing-ci

jobs:
  testing:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Génération du docker-compose pour mariadb
        run: |
          task generate-docker-compose
          echo "mariadb"
        shell: bash